### PR TITLE
workspace: support unicode filenames

### PR DESCRIPTION
**Pull request by artagnon**
Remove ad-hoc handling of uri, and use the Uri module instead. This gives us the benefit of being able to percent-decode, and support unicode filenames.

### CODE REVIEW

**Comment by ejgallego** [comment]
Great, note this likely fixes #187 

What is the story here if the URI is erroneous? Does that library something that returns a `Result.t` ?

**Comment by artagnon** [comment]
The library returns an empty Uri.t on error:

https://github.com/mirage/ocaml-uri/blob/master/lib/uri.ml#L1105-L1112

It doesn't yet fix #187, as we need error handling code if the parse result is empty.

**Comment by ejgallego** [comment]
Indeed, let's introduce a proper OCaml URI type in 0.1.6 and solve #187, thanks a lot for the fix Ram!

By the way folks, you know of a better way to avoid these annoying CHANGES.md conflicts?

**Review by ejgallego — APPROVED** [review]
Looks good to me, tho we want to push this check to the controller layer.

Note that in rq_init we have another instance of bad parsing, maybe that is breaking directories with unicode.

**Review by Alizter — APPROVED** [review]

**Pull request merged**
