### PR TITLE
Add a Petanque TCP server

### PR DESCRIPTION
**Pull request by gbdrt**
Add a Petanque TCP server to communicate with Coq.

Bug fixes:
- `Run_error`: unbound (ocaml 5.1.1)
- Second starts with same args raise `ThmNotFound`

### CODE REVIEW

**Comment by Alizter** [comment]
This PR is aimed at the petanque branch, is that intentional?

**Comment by ejgallego** [comment]
> This PR is aimed at the petanque branch, is that intentional?

Yes, we will put things in `main` soonish, once we get the first working prototype.

In an ideal world we could have developed `petanque` in its own repos, but actually it makes more sense to have a single repos for now due to API coupling and the bad state of multi-repos tooling.

**Comment by ejgallego** [comment]
Ouch, this was closed because I merged the petanque branch! Let me fix the mess.

**Comment by ejgallego** [comment]
Ok, I've rebased this on top of #705 , once #705 goes in we can merge this, but I think we may want to tweak #705 a little bit.

**Comment by ejgallego** [comment]
That was closed because I deleted the branch this depended upon (again).

Sorry for all the noise, will fix ASAP.

**Pull request merged**
