### PR TITLE
elaborate install instructions for editor/code in README

### PR DESCRIPTION
**Pull request by Alizter**
Signed-off-by: Ali Caglayan <alizter@gmail.com>

ps-id: d2201c1b-5331-4393-95a6-97b67d7f7d44

### CODE REVIEW

**Comment by ejgallego** [comment]
> ```
> npm install editor/code
> ```
> 
> will create node_modules in the repo root again. Perhaps we should gitignore before suggesting that?

That's likely not the right command then, we need to look at the vscode plugin dev guide.

**Comment by Alizter** [comment]
@ejgallego The correct command would be to run it inside editor/code.

**Comment by ejgallego** [comment]
Command line command is `code --install-extension myextension.vsix`

**Comment by ejgallego** [comment]
Sure go ahead!

**Pull request merged**
