### PR TITLE
Add a test for checking entire document

### PR DESCRIPTION
**Pull request by artagnon**
The process of writing this test uncovered another bug, which is separately listed as #414.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]

**Review by Alizter — COMMENTED** [review]
Can we record and doff a log of the notifications?

**Comment by artagnon** [comment]
We don't want to clamp down too tightly on what notifications the server sends: the test will break on minor changes to the server. But yes, we do want to diff an error diagnostic for example.

**Comment by ejgallego** [comment]
I merged this too quickly, there is a problem with the test setup on Windows:
https://github.com/ejgallego/coq-lsp/actions/runs/4236164101/jobs/7360654709
```
Test Suites: 2 passed, 2 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        2.883 s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
Terminate batch job (Y/N)? 
Error: The operation was canceled.
```
@artagnon can you have a look? Looks like something silly?

Will be good to put a timeout anyways, 5 hours job is too much IMHO.

**Comment by artagnon** [comment]
Very puzzling. I'm not sure how to debug this Windows-only failure: on macOS, Jest exits just fine, and there are no open handles.

**Comment by ejgallego** [comment]
> Very puzzling. I'm not sure how to debug this Windows-only failure: on macOS, Jest exits just fine, and there are no open handles.

Could it be that we need to pass a timeout to the function? Or set some other kind of timer? But indeed, it is strange.

**Comment by artagnon** [comment]
Jest includes a default timeout of five seconds, but doesn't exit if there are open handles.

**Comment by ejgallego** [comment]
Umm, no idea, I guess we can see if the node vs language client does some special.

https://github.com/microsoft/vscode-languageserver-node/blob/main/client/src/node/main.ts

Certainly we could be missing something in terms of disposing the RPC connections.

**Comment by ejgallego** [comment]
In particular see this https://github.com/microsoft/vscode-languageserver-node/blob/main/client/src/node/processes.ts

**Comment by ejgallego** [comment]
Option `--detectOpenHandles` could be of help here.

**Comment by artagnon** [comment]
Indeed, there seem to be open handles from `cp.spawn()`, and I'm currently investigating.

**Comment by ejgallego** [comment]
CI yielded:
```
Jest has detected the following 2 open handles potentially keeping Jest from exiting:
  ●  PROCESSWRAP
      39 |
      40 | export function start() {
    > 41 |   let childProcess = cp.spawn(serverPath, [], {
         |                         ^
      42 |     env: {
      43 |       ...process.env,
      [44](https://github.com/ejgallego/coq-lsp/actions/runs/4246540796/jobs/7383483174#step:6:45) |       OCAMLPATH: ocamlPath,
      at start (src/LanguageServer.ts:41:25)
      at Object.<anonymous> (src/LanguageServer.ts:59:24)
      at src/LanguageServer.ts:31:71
      at Object.<anonymous>.__awaiter (src/LanguageServer.ts:27:12)
      at Object.startAndInitialize (src/LanguageServer.ts:67:12)
      at src/Check.test.ts:5:[45](https://github.com/ejgallego/coq-lsp/actions/runs/4246540796/jobs/7383483174#step:6:46)
      at src/Check.test.ts:31:71
      at Object.<anonymous>.__awaiter (src/Check.test.ts:27:12)
      at Object.<anonymous> (src/Check.test.ts:4:39)
  ●  PIPEWRAP
      39 |
      40 | export function start() {
    > 41 |   let childProcess = cp.spawn(serverPath, [], {
         |                         ^
      42 |     env: {
      43 |       ...process.env,
      44 |       OCAMLPATH: ocamlPath,
          at Array.reduce (<anonymous>)
      at start (src/LanguageServer.ts:41:25)
      at Object.<anonymous> (src/LanguageServer.ts:59:24)
      at src/LanguageServer.ts:31:71
      at Object.<anonymous>.__awaiter (src/LanguageServer.ts:27:12)
      at Object.startAndInitialize (src/LanguageServer.ts:67:12)
      at src/Check.test.ts:5:45
      at src/Check.test.ts:31:71
      at Object.<anonymous>.__awaiter (src/Check.test.ts:27:12)
      at Object.<anonymous> (src/Check.test.ts:4:39)
      ```

**Comment by ejgallego** [comment]
Seems like connection.dispose may not dispose the stream writer / reader?

**Pull request merged**
