### PR TITLE
chore: update flake

### PR DESCRIPTION
**Pull request by Alizter**

### CODE REVIEW

**Comment by Alizter** [comment]
@ejgallego Looks like serlib isn't building?

**Comment by ejgallego** [comment]
> @ejgallego Looks like serlib isn't building?

That seems pretty odd, I guess a problem with some newer ppx version?

I'll have a look when I can.

**Comment by Alizter** [comment]
There are hardcoded versions in the flake which were causing the issue. I've pushed a fix, let's see if it works.

**Comment by Alizter** [comment]
Looks like it worked. There was a TS formatting issue which I also fixed.

**Comment by Alizter** [comment]
FTR you can easily update the format for nix, TS and ocaml by doing `nix fmt`.

**Pull request merged**
