### PR TITLE
Adapt to coq/coq#19640 (Vernacexpr.debug_univ_name)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by proux01** [comment]
@ejgallego upstream PR merged, please merge

**Comment by ejgallego** [comment]
I will merge, you should folks be able to merge yourself, please let me know if that doesn't work as imagine I'm on holidays for example.

**Comment by ejgallego** [comment]
@proux01 you mind trying pressing the button with this PR?

**Comment by SkySkimmer** [comment]
It only works after you did a force push

**Comment by SkySkimmer** [comment]
something about signature requirements I think

**Comment by proux01** [comment]
> @proux01 you mind trying pressing the button with this PR?

Well, apparently I don't have rights :( (no button shown to me)

**Comment by proux01** [comment]
Sorry, forgot to accept the invitation, done

**Comment by ejgallego** [comment]
> Sorry, forgot to accept the invitation, done

A few Coq devs were already added to the repos, but you were not, fixed now.

> something about signature requirements I think

I need to look into this, the thing is that most projects these days require people that submit a pull request to either:
- sign their commit
- or use a signed-off-by label

for legal reasons, an example is Jane Street open source projects and their DCO.

So indeed I will try to set up things folks so that you can override the signing requirements, but IMHO would be good to raise this issue to the Coq project.

**Pull request merged**
