### PR TITLE
chore(ci): add Nix to CI

### PR DESCRIPTION
**Pull request by Alizter**
I've also removed some duplication between the macos and ubuntu jobs since we can be specific about combinations we actually want to check.

### CODE REVIEW

**Comment by ejgallego** [comment]
Hi @Alizter , what's the milestone for this and #85 ?

**Comment by Alizter** [comment]
@ejgallego issues have been fixed. I've reduced the dune bound in the opam file to 3.2. This can be merged ASAP.

**Review by ejgallego — CHANGES_REQUESTED** [review]
This needs changes:
- dune < 3.5 will make CI fail, so the bound is still needed as long as we have the current setup, bump Nix stuff instead to use 3.5
- please put unrelated changes in their own commits / PRs

**Comment by Alizter** [comment]
@ejgallego the CI seems to be fine with the version, are you sure?

**Comment by ejgallego** [comment]
CI seems fine because it is picking a more up to date version, but if we relax the constraint it would accept non-working configurations.

Indeed we have a problem with the way things are setup, (issue #51 ) , for a non-composed build, we can indeed use Dune 3.2 or lower (see opam file for the v8.16 branch) , however, for the composed build, we need Dune >= 3.5 .

I'm still unsure how to solve this other than indeed separating the dev build setup to something like coq-universe.

Another solution would be to have two opam files, one for developer builds, and one for release builds. Indeed you can see that there are other problems if you diff the 8.16 branch opam file with master; opam handles vendoring not well at all.

**Comment by Alizter** [comment]
OK I dropped touching the Dune version.

**Comment by ejgallego** [comment]
Thanks!

**Pull request merged**
