### PR TITLE
Adapt to coq/coq#18771 (Improve handling of Drop)

### PR DESCRIPTION
**Pull request by afdw**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Please merge now

**Comment by ejgallego** [comment]
@SkySkimmer you folks have permission to merge, the process can be streamlined tho, this is what I do:
```
$ hub checkout https://github.com/ejgallego/coq-lsp/pull/677
$ git rebase main
$ make submodules-update
$ git add vendor/coq vendor/coq-serapi
$ git commit --amend
$ git push --force ....
```

**Comment by SkySkimmer** [comment]
Don't you need some signing stuff?

**Comment by Alizter** [comment]
Issue is https://github.com/ejgallego/coq-lsp/issues/489. We can probably get rid of commit signing. I don't see why it would be useful for us.

**Pull request merged**
