### PR TITLE
Color changes for light color themes.

### PR DESCRIPTION
**Pull request by bhaktishh**
as per #532 .
Screenshot 2023-08-17 at 12 19 20 AM

### CODE REVIEW

**Comment by Alizter** [comment]
@bhaktishh Can you post a screenshot of how it looks?

**Comment by bhaktishh** [comment]
> @bhaktishh Can you post a screenshot of how it looks?

sure, updated.

**Review by ejgallego — APPROVED** [review]
Thanks a lot @bhaktishh ! 

@corwin-of-amber , does this make sense to you?

**Review by ejgallego — CHANGES_REQUESTED** [review]
Actually, @bhaktishh , would you mind adding a CHANGES entry so the imrprovement reaches the changelog?

**Comment by bhaktishh** [comment]
@ejgallego let me know if that works!

**Review by ejgallego — APPROVED** [review]
Thanks!

**Comment by ejgallego** [comment]
Shachar (@corwin-of-amber) noted that it could be useful to look at `coq-light.css` and `coq-dark.css` in jsCoq, links:

- https://github.com/jscoq/jscoq/blob/e2f5e49a1e0cca365ce168ea4c3a8cdcc8d717e5/frontend/classic/css/coq-dark.css
- https://github.com/jscoq/jscoq/blob/e2f5e49a1e0cca365ce168ea4c3a8cdcc8d717e5/frontend/classic/css/coq-light.css

**Pull request merged**
