### PR TITLE
[fleche] Add children info to the table-of-contents

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by Alizter** [comment]
I'm confused, was this to do with the document symbols?

**Comment by ejgallego** [comment]
The table of contents is used for jump to definition. So now jumping to children works.

**Comment by ejgallego** [comment]
A better name we will use is some kind of `Index.t`

**Comment by ejgallego** [comment]
So in this sense we have the map `definition -> range` and the list of definitions.

**Pull request merged**
