### PR TITLE
Adapt to coq/coq#17098 (functional gramlib)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ppedrot** [comment]
Please merge.

**Comment by artagnon** [comment]
@ppedrot Please bump the coq submodule in the same commit, so that the build passes.

**Comment by artagnon** [comment]
@ppedrot You're also required to sign your commits with a GPG key for coq-lsp.

**Comment by SkySkimmer** [comment]
Why is there a coq submodule? You are supposed to use master for your CI

**Comment by Alizter** [comment]
@SkySkimmer Would you like me to fix this PR and merge?

**Comment by SkySkimmer** [comment]
yes

**Comment by ejgallego** [comment]
Yes, we need modify the build setup for coq-lsp now tracking `master`, this is #51 ; I will fix it ASAP.

We use submodules because historically, and until very recently, `coq-lsp` only worked with a patched Coq, but fortunately we were able to push most patches upstream.

**Comment by ejgallego** [comment]
Actually also I was experimenting here with something that we have discussed often in Coq: pinning the CI deps.

On one hand this gives us more reproducibility, and a way to test overlays easier.

**Comment by ejgallego** [comment]
I'm not sure either, it is related to dev setup so really not something that will any impact on releases as these build against released Coq versions.

**Pull request merged**
