### PR TITLE
ci: Replace nix fmt with flake check

### LINKED ISSUE #449: [ci] Format job doesn't fail anymore on incorrectly formatted sources.
See build log https://github.com/ejgallego/coq-lsp/actions/runs/4339317524/jobs/7576789585

This seems to originate in #284 , cc @Alizter @r-muhairi

### PR DESCRIPTION
**Pull request by r-muhairi**
Closes #449

### CODE REVIEW

**Comment by Alizter** [comment]
So `nix fmt` formats the nix files and `nix check` actually runs ftmtree (which in turn runs all our formatters)?

**Comment by r-muhairi** [comment]
> So `nix fmt` formats the nix files and `nix check` actually runs fmttree (which in turn runs all our formatters)?

nix fmt runs the `formatter` output generated by treefmt.config.??? not sure what was the option

nix flake check runs all the `checks` outputs found in `nix flake show` set through for example checks.something = drv;

All checks set are run through `nix flake check` I don't personally know if it is possible to run a specific target, but yeah.

The available checks are for treefmt set by using treefmt flake module.

**Comment by Alizter** [comment]
I reread the code we have an I am not entirely sure how ocamlformat is being run. Where do we run that? Is it just using the makefile?

**Comment by Alizter** [comment]
As a test, could you push a commit messing up the formatting in an ml file, a typescript file and a nix file to see how the CI complains?

**Comment by r-muhairi** [comment]
> I reread the code we have an I am not entirely sure how ocamlformat is being run. Where do we run that? Is it just using the makefile?

If you look at the checks output in `nix flake show` you'll see a new check added on enabling treefmt
treefmt-nix comes with a predefined check using your treefmt.config setup, so it's just basically running treefmt behind the scenes with a TOML generated from our nix setup and a couple of extra flags for just checking not formatting and etc.

> As a test, could you push a commit messing up the formatting in an ml file, a typescript file and a nix file to see how the CI complains?

Done

**Comment by Alizter** [comment]
Excellent thanks!

**Comment by ejgallego** [comment]
Thanks a lot folks!

**Pull request merged**
