### PR TITLE
fleche, editor: strip Ok_diagnostic feature

### PR DESCRIPTION
**Pull request by artagnon**
Since the introduction of #106, this feature is redundant, and only serves to choke up notifications in VSCode.

### CODE REVIEW

**Review by ejgallego — CHANGES_REQUESTED** [review]
Nack, this is a very useful debug tool for me.

**Comment by Alizter** [comment]
I am also unsure why this is considered redundant. Could you elaborate?

**Comment by ejgallego** [comment]
I guess you can indeed determine when a sentence has been processed from the range sent in `fileProgress`.

We could also implement this in hover; so thinking a bit more about it, @artagnon is right about this functionality being a bit silly, however it is not clear if this functionality could be useful for other non-vscode clients.

I suggest we put this in the 0.2 milestone and discuss about it in the coq-lsp dev meeting that I plan to announce shortly.

**Comment by ejgallego** [comment]
Moreover:
- this needs a changes entry
- while we have not been following semantic versioning, I hope that starting with 0.2 we do , so changes like this would have to wait for a minor release. Tho, due to some constraints client/server, our versioning scheme may be complex, at this stage it seems overkill to me to have to bump a minor version to change the goals request for example. Let's discuss about this.

**Comment by Alizter** [comment]
I am OK with this in the end. I haven't used the Ok_diagnostic feature at all during debugging and I agree with @artagnon that it is no longer needed. Can you rebase?

**Comment by ejgallego** [comment]
Now we have indeed the `fileProgress` notification which kind of serves the same purpose.

I'm still unsure if some other clients may want this, but I'm happy if you folks wanna get rid of this.

**Comment by Alizter** [comment]
@ejgallego If clients want to have a "green highlighting feature" as we have discussed in the past, we should make it a custom LSP notification rather than hacking it into existing (unrelated) LSP notifications.

**Comment by ejgallego** [comment]
> @ejgallego If clients want to have a "green highlighting feature" as we have discussed in the past, we should make it a custom LSP notification rather than hacking it into existing (unrelated) LSP notifications.

File progress works for that actually, what would be missing?

But note that the LSP protocol diagnostics are are only for errors and warnings, our use case is supported, it is just that the clients don't scale well it seems.

**Comment by Alizter** [comment]
My thought would be to have a notification that simply emits a range in the document rather than a bunch of them. That would scale better.

**Review by ejgallego — APPROVED** [review]

**Pull request merged**
