### PR TITLE
[dev] Update ocamlformat to 0.26.0

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by ejgallego** [comment]
@Alizter this needs a nix update but I'm unsure how to do it; maybe we should add how to bump the flake deps to the contributing guide? TIA!

**Comment by Alizter** [comment]
@ejgallego I'll take a look.

**Comment by Alizter** [comment]
@ejgallego You can update this now.

**Comment by ejgallego** [comment]
Yes, thanks. I saw my opam updated to 0.26.1 and I tried my luck XD

**Pull request merged**
