### PR TITLE
[vscode] Syntax highlighting for Coq 8.17-8.20

### PR DESCRIPTION
**Pull request by 4ever2**
Add updated syntax from VSCoq Legacy and extend with new commands from Coq 8.17-8.20

### CODE REVIEW

**Comment by Alizter** [comment]
Did you cover the list in #854? I haven't been able to fully check myself yet.

**Comment by 4ever2** [comment]
Not all of them are covered by this PR. Some of them seem quite hard to fix.
I don't think there is a good way to fix highlighting on `Set`.

**Comment by Alizter** [comment]
I guess to do `Set` correctly you will have to look at all the options. IIRC there should be a vernac command that prints the options table, so that might be a way to start on such a list.

I can't tell if `Register some_constant.` will get highlighted, I can see `Register Scheme` is picked up.

Also, I can't tell if `Add Search Blacklist` is also considered.

I've updated the list accordingly since presumably we will merge this anyway.

**Comment by 4ever2** [comment]
`Register some_constant.` will highlight `Register` as a command but not `some_constant` as an ident.
`Add Search Blacklist` is not considered here.

**Comment by Alizter** [comment]
> `Register some_constant.` will highlight `Register` as a command but not `some_constant` as an ident.

That's fine, as long as `Register` is being picked up.

**Pull request merged**
