### PR TITLE
[ci] [v8.19] Try to make CI green again.

### PR DESCRIPTION
**Pull request by ejgallego**
- Windows special config for Coq should not be needed, as we don't build Coq ourselves
- Nix disabled due to #522

### CODE REVIEW

**Comment by Alizter** [comment]
I didn't realise that Nix was an issue on the main branch, I thought it was failing for older versions of Coq?

**Comment by ejgallego** [comment]
> I didn't realise that Nix was an issue on the main branch, I thought it was failing for older versions of Coq?

Yes, that's the case. Nix is OK in the main branch, but it fails on stable versions, so I'm disabling it for now as to get a green CI (red CI did hide other issues)

**Comment by Alizter** [comment]
@ejgallego Oh I misread then. I think its fine to have no nix tests in the stable branches as the flake is really about the development version or more rather helping with development. We distribute stable coq-lsp in nixpkgs anyway. The PR for 8.18 has been recently merged for example: https://github.com/NixOS/nixpkgs/pull/288185

**Comment by ejgallego** [comment]
Indeed, that's what this PR is about, maybe you missed the base branch?

**Comment by ejgallego** [comment]
So you then think is a good idea to mark #522 as solved by this PR?

**Comment by ejgallego** [comment]
Note that the CI is for _stable_ Coq versions, however we test the development branch of coq-lsp

**Comment by Alizter** [comment]
I think that issue should stay open, maybe somebody can fix the nix stuff for the stable branches. I'm not particularly interested in spending time on that however. As long as we continue to test the dev branch with nix I am ok.

**Pull request merged**
